use_frameworks!

platform :ios, '11.0'

target 'RandomNumberTextField_Example' do
  pod 'RandomNumberTextField', :path => '../'

  target 'RandomNumberTextField_Tests' do
    inherit! :search_paths

    
  end
end
